### ISSUE TITLE
Crash after install and first dir change: "sre_constants.error: unterminated character set at position 0"

### ISSUE THREAD

**Issue by andrbmgi** [wting/autojump#543]
```
Traceback (most recent call last):
  File "C:\Users\xxxx\AppData\Local\autojump\bin\\autojump", line 342, in <module>
    sys.exit(main(parse_arguments()))
  File "C:\Users\xxxx\AppData\Local\autojump\bin\\autojump", line 308, in main
    ['.'],
  File "C:\Users\xxxx\AppData\Local\autojump\bin\autojump_utils.py", line 41, in first
    return it.__next__()
  File "C:\Users\xxxx\AppData\Local\autojump\bin\autojump_match.py", line 86, in <lambda>
    flags=regex_flags,
  File "C:\Python36\lib\re.py", line 182, in search
    return _compile(pattern, flags).search(string)
  File "C:\Python36\lib\re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Python36\lib\sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Python36\lib\sre_parse.py", line 855, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\Python36\lib\sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "C:\Python36\lib\sre_parse.py", line 523, in _parse
    source.tell() - here)
sre_constants.error: unterminated character set at position 0
ECHO ist ausgeschaltet (OFF).
```

**Comment by xyfigo** [comment]
how to do with this problem?

**Comment by MrKriss** [comment]
I'm running Windows 10 and encountered very similar problem to this and #522. I found that the underlying cause was #436, as once I implemented the suggested fix this issue went away.

**Comment by dirad** [comment]
I seem to have the same issue, but modifying autojump_match.py like in https://github.com/wting/autojump/issues/434 didn't solve it for me.

**Comment by dirad** [comment]
> 

Perhaps it is due to something else? ;
 I've now noticed that opening bash via cmder, I get an error message related to Python
```
C:\Users\Ad\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\win_unicode_console\__init__.py:31: RuntimeWarning: sys.stdin.encoding == 'utf-8', whereas sys.stdout.encoding == 'cp65001', readline hook consumer may assume they are the same
  readline_hook.enable(use_pyreadline=use_pyreadline)
```

This doesnt happen in any other terminal, nor in git-bash, which uses mintty.
